### ISSUE TITLE
not working with ExtendScript Debugger v2

### ISSUE THREAD

**Issue by mamoworld** [axwt/texttojsxbin#8]
After installing ExtendScript Debugger 2.0.0 RC1, TextToJsxbin is not working anymore. I get this error message:

Command 'TextToJSXBIN' resulted in an error (Cannot find module '/Users/mmohl/.vscode/extensions/adobe.extendscript-debug-2.0.0-rc1/node_modules/@esdebug/esdebugger-core/mac/esdcorelibinterface.node'
Require stack:
- /Users/mmohl/.vscode/extensions/motionland.texttojsxbin-0.0.5/out/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js)

I checked, why this cannot be found and noticed that here does not exist a module @esdebug in 
.vscode/extensions/adobe.extendscript-debug-2.0.0-rc1/node_modules/

Is TextToJsxbin not compatible with V2 of the debugger? Do you have plans to support it?

**Comment by axwt** [comment]
A bit late, but the update is available now.

**Comment by mamoworld** [comment]
Amazing, thank you!

**Comment by mamoworld** [comment]
Where can I find the update? VSCode still shows me v0.0.5 from 2019 as latest version.

**Comment by axwt** [comment]
I'll post the update on the VS Code market soon

**Comment by axwt** [comment]
I just posted the update.

**Comment by mamoworld** [comment]
Works like a charm - thank you :-)
